site_name: Haikara Wiki
site_description: Persönliches Wissens-Wiki

theme:
  name: material
  custom_dir: docs/overrides
  language: de
  font:
    text: Syne
    code: JetBrains Mono
  palette:
    scheme: slate
    primary: custom
    accent: custom
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - search.suggest
    - search.highlight
    - content.code.copy

extra_css:
  - stylesheets/extra.css

plugins:
  - search:
      lang: de

nav:
  - Start: index.md
  - Berufsschule:
    - Übersicht: berufsschule/index.md
    - LF01 – Lernfeld 01:
      - berufsschule/lf01/index.md
    - LF02 – Lernfeld 02:
      - berufsschule/lf02/index.md
    - LF03 – Lernfeld 03:
      - berufsschule/lf03/index.md
    - LF04 – Lernfeld 04:
      - berufsschule/lf04/index.md
    - LF05 – Lernfeld 05:
      - berufsschule/lf05/index.md
    - LF06 – Lernfeld 06:
      - berufsschule/lf06/index.md
    - LF07 – Lernfeld 07:
      - berufsschule/lf07/index.md
    - LF08 – Lernfeld 08:
      - berufsschule/lf08/index.md
    - LF09 – Lernfeld 09:
      - berufsschule/lf09/index.md
      - TestdokumentDie10t: berufsschule/lf09/testdokumentdie10t.md
    - LF10 – Lernfeld 10:
      - berufsschule/lf10/index.md
    - LF11 – Lernfeld 11:
      - berufsschule/lf11/index.md
    - LF12 – Lernfeld 12:
      - berufsschule/lf12/index.md
    - LF3W – Lernfeld 3W:
      - berufsschule/lf3w/index.md
    - LF8W – Lernfeld 8W:
      - berufsschule/lf8w/index.md
    - WSK:
      - berufsschule/wsk/index.md
    - Englisch:
      - berufsschule/englisch/index.md
    - Sport:
      - berufsschule/sport/index.md
  - Notizen:
    - notizen/index.md

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: ios
          class: ios
          format: !!python/name:pymdownx.superfences.fence_code_format
        - name: cisco
          class: cisco
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - attr_list
  - md_in_html
  - tables
