site_name: Haikara Wiki
site_description: Persönliches Wissens-Wiki

theme:
  name: material
  custom_dir: docs/overrides
  language: de
  font:
    text: Syne
    code: JetBrains Mono
  palette:
    scheme: slate
    primary: custom
    accent: custom
  features:
    - navigation.tabs
    - navigation.indexes
    - navigation.prune
    - navigation.top
    - search.suggest
    - search.highlight
    - content.code.copy

extra_css:
  - stylesheets/extra.css

hooks:
  - hooks/meta_bar.py

plugins:
  - search:
      lang: de

nav:
  - Start: index.md
  - Berufsschule:
    - Übersicht: berufsschule/index.md
    - LF01:
      - berufsschule/lf01/index.md
      - Untitled234: berufsschule/lf01/untitled234.md
    - LF02:
      - berufsschule/lf02/index.md
    - LF03:
      - berufsschule/lf03/index.md
    - LF3W:
      - berufsschule/lf3w/index.md
    - LF04:
      - berufsschule/lf04/index.md
    - LF05:
      - berufsschule/lf05/index.md
    - LF06:
      - berufsschule/lf06/index.md
    - LF07:
      - berufsschule/lf07/index.md
    - LF08:
      - berufsschule/lf08/index.md
    - LF8W:
      - berufsschule/lf8w/index.md
    - LF09:
      - berufsschule/lf09/index.md
      - Untitled: berufsschule/lf09/untitled.md
      - ThisIsTitled: berufsschule/lf09/thisistitled.md
    - LF10:
      - berufsschule/lf10/index.md
    - LF11:
      - berufsschule/lf11/index.md
    - LF12:
      - berufsschule/lf12/index.md
    - WSK:
      - berufsschule/wsk/index.md
    - Englisch:
      - berufsschule/englisch/index.md
    - Sport:
      - berufsschule/sport/index.md
  - Notizen:
    - notizen/index.md

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: ios
          class: ios
          format: !!python/name:pymdownx.superfences.fence_code_format
        - name: cisco
          class: cisco
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - attr_list
  - md_in_html
  - tables
